// Generated by LiveScript 1.2.0
(function(){
  var Enemy0, tr;
  let count = 0;
  importScripts('/robocode/scripts/base-robot.js');
  Enemy0 = (function(superclass){
    var prototype = extend$((import$(Enemy0, superclass).displayName = 'Enemy0', Enemy0), superclass).prototype, constructor = Enemy0;
    prototype.onIdle = function(){
      this.turn_turret_right(45);
      if(count == 1000){      
        this.move_forwards(50);
        count = 0;
      }
      count++;
        
    };
    prototype.onWallCollide = function(){};
    prototype.onHit = function(){
      this.yell("Oops!");
    };
    prototype.onEnemySpot = function(){
      this.enemySpot.forEach(element => {
        if(element.id == 0){
          this.yell("Fire!");
          this.shoot();
        }
      });
    };
    function Enemy0(){
      Enemy0.superclass.apply(this, arguments);
    }
    return Enemy0;
  }(BaseRobot));
  tr = new Enemy0("Enemy 0");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
