// Generated by LiveScript 1.2.0
(function(){
  var Enemy2, tr;
  importScripts('/robocode/scripts/base-robot.js');
  Enemy2 = (function(superclass){
    var prototype = extend$((import$(Enemy2, superclass).displayName = 'Enemy2', Enemy2), superclass).prototype, constructor = Enemy2;
    prototype.onIdle = function(){
      this.turn_right(10);
      this.turn_turret_right(180);
      this.move_forwards(100);
      if (Math.random() > 0.5) {
        this.turn_right(30);
      } else {
        this.turn_left(30);
      }
    };
    prototype.onWallCollide = function(){
      this.move_opposide(10);
      this.turn_left(90);
    };
    prototype.onHit = function(){
      this.turn_right(30);
      this.move_forwards(50);
    };
    prototype.onEnemySpot = function(){
      this.shoot();
    };
    function Enemy2(){
      Enemy2.superclass.apply(this, arguments);
    }
    return Enemy2;
  }(BaseRobot));
  tr = new Enemy2("Enemy 2");
  function extend$(sub, sup){
    function fun(){} fun.prototype = (sub.superclass = sup).prototype;
    (sub.prototype = new fun).constructor = sub;
    if (typeof sup.extended == 'function') sup.extended(sub);
    return sub;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
